import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { transformSync } from 'esbuild';
import * as React from 'react';
import * as jsxRuntime from 'react/jsx-runtime';
import { create, act } from 'react-test-renderer';
import { useDebouncedValue } from '../src/hooks/useDebouncedValue.js';
import * as search from '../src/utils/leadSearch.js';
import * as leadData from '../src/utils/leadData.js';
import * as dates from '../src/utils/dateTime.js';
import * as health from '../src/utils/followupHealth.js';
import { isRequestCancelled } from '../src/services/queryCache.js';
const deferred = () => { let resolve;const promise = new Promise(r=>{resolve=r;});return{promise,resolve}; };
const sleep = ms => new Promise(r=>setTimeout(r,ms));
test('Leads waits for preferences, debounces, aborts stale results, shows filter chips and never syncs on mount',async t=>{
 const prefs=deferred(),calls=[];let syncs=0;
 const empty=async()=>({data:{stages:[],staff:[],campaigns:[]}});
 const apis={automationAPI:{getSequences:empty},authAPI:{getPreferences:()=>prefs.promise,updatePreferences:empty},stageAPI:{getAll:empty},statusAPI:{byStage:empty},staffAPI:{getAll:empty},campaignAPI:{getAll:empty},integrationsAPI:{facebookSyncStatus:async()=>({data:{configured:true,last_synced_at:'2026-09-30T10:00:00Z'}}),facebookSyncLeads:async()=>{syncs++;return{data:{created:0}};}},leadAPI:{getAll:(params,options)=>{const pending=deferred();calls.push({params,signal:options.signal,...pending});return pending.promise;}}};
 const noop=()=>{};const storage=new Map();const module={exports:{}};
 const code=transformSync(readFileSync(new URL('../src/pages/LeadsPage.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs',jsx:'automatic'}).code;
 const location={search:'',state:null};
 vm.runInNewContext(code,{module,exports:module.exports,console,URLSearchParams,Date,setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,
  localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},document:{addEventListener:noop,removeEventListener:noop},window:{addEventListener:noop,removeEventListener:noop},
  require(name){
   if(name==='react')return React;
   if(name==='react/jsx-runtime')return jsxRuntime;
   if(name==='react-dom')return{createPortal:x=>x};
   if(name==='react-router-dom')return{useLocation:()=>location,useNavigate:()=>()=>{}};
   if(name==='lucide-react')return new Proxy({},{get:()=> 'span'});
   if(name.includes('services/api'))return apis;
   if(name.includes('queryCache'))return{isRequestCancelled};
   if(name.includes('useDebouncedValue'))return{useDebouncedValue};
   if(name.includes('utils/leadSearch'))return search;
   if(name.includes('utils/leadData'))return leadData;
   if(name.includes('utils/dateTime'))return dates;
   if(name.includes('utils/followupHealth'))return health;
   if(name.includes('AuthContext'))return{useAuth:()=>({user:{id:'u',role:'admin'},tenant:{id:'t'}})};
   if(name.includes('ConfirmDialog'))return{useConfirmDialog:()=>noop};
   if(name.includes('Toast'))return{useToast:()=>({error:noop,success:noop})};
   return {default:()=>null};
  }});
 let renderer; t.after(async()=>{if(renderer) await act(async()=>renderer.unmount());});
 await act(async()=>{renderer=create(React.createElement(module.exports.default));});
 assert.equal(calls.length,0);assert.equal(syncs,0);
 await act(async()=>prefs.resolve({data:{preferences:{hidden_lead_stages:['unqualified','lost']}}}));
 assert.equal(calls.length,1);assert.equal(calls[0].params.hide_stages,'unqualified,lost');
 assert.equal(renderer.root.findAllByProps({'aria-label':'Show lost leads'}).length,1);
 const input=()=>renderer.root.findByProps({placeholder:'Search by name, phone or lead ID...'});
 await act(async()=>input().props.onChange({target:{value:'Har'}}));assert.equal(calls[0].signal.aborted,true);
 await act(async()=>{await sleep(50);input().props.onChange({target:{value:'Harish'}});});
 assert.equal(calls.length,1);
 await act(async()=>{await sleep(330);});assert.equal(calls.length,2);assert.equal(calls[1].params.search,'Harish');assert.equal(calls[1].params.hide_stages,'unqualified,lost');
 await act(async()=>input().props.onChange({target:{value:'Sunita'}}));assert.equal(calls[1].signal.aborted,true);
 await act(async()=>{await sleep(330);});assert.equal(calls.length,3);
 await act(async()=>calls[2].resolve({data:{leads:[],pagination:{total:42,pages:2},search_mode:'direct'}}));
 const current=JSON.stringify(renderer.toJSON());
 await act(async()=>{calls[0].resolve({data:{leads:[],pagination:{total:999,pages:99}}});calls[1].resolve({data:{leads:[],pagination:{total:999,pages:99}}});});
 assert.equal(JSON.stringify(renderer.toJSON()),current,'old responses must not change current results');
 assert.equal(syncs,0);
 await act(async()=>renderer.root.findByProps({'aria-label':'Show lost leads'}).props.onClick());
 assert.equal(calls.at(-1).params.hide_stages,'unqualified');
});
